import Head from 'next/head';
import Image from 'next/image';
import Hero from '../components/Hero';
import Display from '../components/Display';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Fadhila Zalfa Alisya</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading='Hello, Welcome to ELAYNE' message='Happy Shopping Everyone!' />
      <Display/>
    </div>
  );
}
